source 'https://rubygems.org'

ruby '2.2.1'

# I wish Rails 5 was out.
gem 'sinatra'
# ActiveRecord is just too good.
gem 'sinatra-activerecord'
# Events are what drive 'Merica.
gem 'thin'
# MariaDB runs off of the same adapter as MySQL.
gem 'mysql2'
