require 'rubygems'
require 'sinatra/activerecord/rake'

# Add Sinatra tasks to rake
namespace :db do
  task :load_config do
    require './server.rb'
  end
end

# Ensure that FactoryGirl factories are valid before running the test suite
if defined?(RSpec)
  desc 'Run factory specs.'
  RSpec::Core::RakeTask.new(:factory_specs) do |t|
    t.pattern = './spec/factories_spec.rb'
  end
end
task spec: :factory_specs
